// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint "cpumem/pkg/endpoint"
	http1 "cpumem/pkg/http"
	service "cpumem/pkg/service"
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	http "github.com/go-kit/kit/transport/http"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"GetCPU":        {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetCPU", logger))},
		"GetMEM":        {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetMEM", logger))},
		"GetNamespaces": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetNamespaces", logger))},
		"GetPods":       {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetPods", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["GetCPU"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetCPU")), endpoint.InstrumentingMiddleware(duration.With("method", "GetCPU"))}
	mw["GetMEM"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetMEM")), endpoint.InstrumentingMiddleware(duration.With("method", "GetMEM"))}
	mw["GetNamespaces"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetNamespaces")), endpoint.InstrumentingMiddleware(duration.With("method", "GetNamespaces"))}
	mw["GetPods"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "GetPods")), endpoint.InstrumentingMiddleware(duration.With("method", "GetPods"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"GetCPU", "GetMEM", "GetNamespaces", "GetPods"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
