// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	service "faasapi/pkg/service"
	endpoint "github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	ListFunctionsEndpoint  endpoint.Endpoint
	InvokeFunctionEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.FaasapiService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		InvokeFunctionEndpoint: MakeInvokeFunctionEndpoint(s),
		ListFunctionsEndpoint:  MakeListFunctionsEndpoint(s),
	}
	for _, m := range mdw["ListFunctions"] {
		eps.ListFunctionsEndpoint = m(eps.ListFunctionsEndpoint)
	}
	for _, m := range mdw["InvokeFunction"] {
		eps.InvokeFunctionEndpoint = m(eps.InvokeFunctionEndpoint)
	}
	return eps
}
